# Configuração do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:estoquedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite acessar o painel do banco de dados pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Pede para o Hibernate (Spring Data JPA) criar as tabelas automaticamente baseado no nosso código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true